'use client'

import { useEffect, useState, useRef } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { useSession, getMembership } from '@/lib/session'
import { CHAT_COMPONENTS, COMPONENT_LABELS, COMPONENT_DESCRIPTIONS, ChatComponent } from '@/lib/chat-components'
import { WaitingRoom } from '@/components/WaitingRoom'

interface Agreement {
  component: string
  resolution_note: string | null
  draft_text: string | null
  final_text: string | null
  recorded_by: string | null
}

interface Approval {
  component: string
  member_id: string
}

interface Reflection {
  member_id: string
  display_name: string
  component: string
  response_data: Record<string, unknown>
}

type ComponentStatus = 'needs_resolution' | 'needs_draft' | 'needs_approval' | 'approved'

const RESOLUTION_PLACEHOLDERS: Record<ChatComponent, string> = {
  object: 'e.g. Annie wants a polished final product, Alan wants to learn new skills. We agreed to aim for both by splitting research and presentation.',
  subject: 'e.g. Annie sees herself leading coordination, Alan prefers deep execution. We agreed on a lead/support split that rotates per task.',
  division_of_labor: 'e.g. Annie takes design and front-end, Alan takes data and testing. We\'ll check in if scope shifts.',
  rules: 'e.g. We agreed to use Slack for daily updates, meet Thursdays, and make decisions by consensus unless one person owns that area.',
  tools: 'e.g. We agreed on Figma for design, GitHub for code, and Notion for notes. Annie will set up shared access.',
  community: 'e.g. We agreed the instructor has input on scope but not day-to-day decisions. Group members decide how we work.',
}

export default function AgreePage() {
  const { code } = useParams<{ code: string }>()
  const router = useRouter()
  const { loading, user, memberships } = useSession()
  const membership = getMembership(memberships, code)

  const [teamId, setTeamId] = useState('')
  const [teamSize, setTeamSize] = useState(2)
  const [flaggedComponents, setFlaggedComponents] = useState<string[]>([])
  const [agreements, setAgreements] = useState<Record<ChatComponent, Agreement | null>>({} as Record<ChatComponent, Agreement | null>)
  const [approvals, setApprovals] = useState<Approval[]>([])
  const [activeComponent, setActiveComponent] = useState<ChatComponent>('object')
  const [resolutionNote, setResolutionNote] = useState('')
  const [editText, setEditText] = useState('')
  const [editDirty, setEditDirty] = useState(false)
  const [generating, setGenerating] = useState<Record<string, boolean>>({})
  const [saving, setSaving] = useState(false)
  const [members, setMembers] = useState<{ id: string; display_name: string }[]>([])
  const [reflections, setReflections] = useState<Reflection[]>([])
  const [aiComments, setAiComments] = useState<Record<ChatComponent, string>>({} as Record<ChatComponent, string>)
  const autoGeneratedRef = useRef<Set<string>>(new Set())
  const editDirtyRef = useRef(false)
  const activeComponentRef = useRef<ChatComponent>('object')

  useEffect(() => {
    if (loading) return
    if (!user || !membership) { router.replace('/'); return }
    loadAll()
    const interval = setInterval(loadAll, 4000)
    return () => clearInterval(interval)
  }, [code, loading, user, membership])

  async function loadAll() {
    const teamRes = await fetch(`/api/teams/${code.toUpperCase()}`)
    if (!teamRes.ok) return
    const teamData = await teamRes.json()
    setTeamId(teamData.id)
    setTeamSize(teamData.status.teamSize)
    setMembers(teamData.members)

    let currentFlagged: string[] = []
    const aiRes = await fetch(`/api/reveal-ai/${code.toUpperCase()}`)
    if (aiRes.ok) {
      const aiData = await aiRes.json()
      currentFlagged = aiData.flagged_components ?? []
      setFlaggedComponents(currentFlagged)
      setAiComments(aiData.per_component ?? {})
    }

    const refRes = await fetch(`/api/reflections/${code.toUpperCase()}`)
    if (refRes.ok) {
      const refData = await refRes.json()
      setReflections(refData.reflections ?? [])
    }

    const agRes = await fetch(`/api/agreements?teamId=${teamData.id}`)
    if (agRes.ok) {
      const agData = await agRes.json()
      const map: Record<ChatComponent, Agreement | null> = {} as Record<ChatComponent, Agreement | null>
      for (const comp of CHAT_COMPONENTS) map[comp] = null
      for (const ag of agData.agreements) map[ag.component as ChatComponent] = ag
      setAgreements(map)
      setApprovals(agData.approvals)

      // Sync edit text if user hasn't made local changes
      if (!editDirtyRef.current) {
        const serverText = map[activeComponentRef.current]?.final_text ?? ''
        if (serverText) setEditText(serverText)
      }

      // Auto-generate drafts for non-flagged components that don't have one yet
      for (const comp of CHAT_COMPONENTS) {
        const isFlagged = currentFlagged.includes(comp)
        const hasDraft = !!map[comp]?.final_text
        if (!isFlagged && !hasDraft && !autoGeneratedRef.current.has(comp)) {
          autoGeneratedRef.current.add(comp)
          generateDraft(comp, teamData.id, undefined)
        }
      }
    }
  }

  async function generateDraft(comp: ChatComponent, tid: string, note: string | undefined) {
    setGenerating(g => ({ ...g, [comp]: true }))
    await fetch('/api/agreements', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        teamId: tid,
        component: comp,
        resolutionNote: note?.trim() || undefined,
        memberId: membership!.member_id,
      }),
    })
    await loadAll()
    setGenerating(g => ({ ...g, [comp]: false }))
  }

  // Reset both fields when switching components
  useEffect(() => {
    activeComponentRef.current = activeComponent
    const ag = agreements[activeComponent]
    setResolutionNote(ag?.resolution_note ?? '')
    setEditText(ag?.final_text ?? '')
    setEditDirty(false)
    editDirtyRef.current = false
  }, [activeComponent])

  if (loading || !user || !membership) {
    return (
      <main className="min-h-screen bg-stone-50 flex items-center justify-center p-6">
        <WaitingRoom message="Loading" subMessage="Just a moment" />
      </main>
    )
  }

  async function handleSaveText() {
    if (!teamId || !editText.trim()) return
    setSaving(true)
    await fetch('/api/agreements', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ teamId, component: activeComponent, finalText: editText, memberId: membership!.member_id }),
    })
    await loadAll()
    setSaving(false)
    setEditDirty(false)
    editDirtyRef.current = false
  }

  async function handleApprove() {
    if (!teamId) return
    await fetch('/api/agreements/approve', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ teamId, component: activeComponent, memberId: membership!.member_id }),
    })
    await loadAll()
  }

  async function handleWithdraw() {
    if (!teamId) return
    await fetch('/api/agreements/approve', {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ teamId, component: activeComponent, memberId: membership!.member_id }),
    })
    await loadAll()
  }

  function getStatus(comp: ChatComponent): ComponentStatus {
    const isFlagged = flaggedComponents.includes(comp)
    const ag = agreements[comp]
    const compApprovals = approvals.filter(a => a.component === comp)
    if (compApprovals.length >= teamSize) return 'approved'
    if (ag?.final_text) return 'needs_approval'
    if (isFlagged) return 'needs_resolution'
    return 'needs_draft'
  }

  const totalApproved = CHAT_COMPONENTS.filter(c => getStatus(c) === 'approved').length
  const allDone = totalApproved === CHAT_COMPONENTS.length

  const ag = agreements[activeComponent]
  const isFlagged = flaggedComponents.includes(activeComponent)
  const compApprovals = approvals.filter(a => a.component === activeComponent)
  const myApproval = compApprovals.some(a => a.member_id === membership?.member_id)
  const fullyApproved = compApprovals.length >= teamSize
  const status = getStatus(activeComponent)

  // Reflections for this component
  const compReflections = reflections.filter(r => r.component === activeComponent)

  function formatResponse(data: Record<string, unknown>): string {
    return Object.entries(data)
      .filter(([k]) => !k.endsWith('_other'))
      .map(([, v]) => {
        if (Array.isArray(v)) return v.join(', ')
        if (v && typeof v === 'object') {
          return Object.entries(v as Record<string, string>)
            .map(([opt, level]) => `${opt}: ${level}`)
            .join(', ')
        }
        return v as string
      })
      .filter(Boolean)
      .join(' · ')
  }

  const STATUS_LABELS: Record<ComponentStatus, string> = {
    needs_resolution: 'Needs discussion',
    needs_draft: 'Generating…',
    needs_approval: 'Needs approval',
    approved: 'Agreed',
  }

  const STATUS_COLORS: Record<ComponentStatus, string> = {
    needs_resolution: 'bg-amber-100 text-amber-700 border-amber-200',
    needs_draft: 'bg-stone-100 text-stone-500 border-stone-200',
    needs_approval: 'bg-blue-50 text-blue-700 border-blue-200',
    approved: 'bg-green-100 text-green-700 border-green-200',
  }

  return (
    <main className="min-h-screen bg-stone-50 p-4 md:p-8">
      <div className="max-w-3xl mx-auto">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-stone-800">Group Agreements</h1>
          <p className="text-stone-500 text-sm mt-1">
            {totalApproved} of {CHAT_COMPONENTS.length} components agreed · {teamSize} approvals needed each
          </p>
        </div>

        {/* Component tabs */}
        <div className="flex gap-2 flex-wrap mb-6">
          {CHAT_COMPONENTS.map(comp => {
            const s = getStatus(comp)
            return (
              <button
                key={comp}
                onClick={() => setActiveComponent(comp)}
                className={`px-3 py-1.5 rounded-full text-xs font-medium border transition ${
                  activeComponent === comp
                    ? 'bg-green-700 text-white border-green-700'
                    : STATUS_COLORS[s]
                }`}
              >
                {s === 'approved' ? '✓ ' : s === 'needs_resolution' ? '⚠ ' : ''}{COMPONENT_LABELS[comp]}
              </button>
            )
          })}
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-stone-100 p-6 mb-4">
          {/* Header */}
          <div className="flex items-start justify-between mb-2">
            <div>
              <h2 className="text-lg font-bold text-stone-800">{COMPONENT_LABELS[activeComponent]}</h2>
              <p className="text-xs text-stone-400 mt-0.5">{COMPONENT_DESCRIPTIONS[activeComponent]}</p>
            </div>
            <span className={`text-xs font-semibold px-2.5 py-1 rounded-full border ${STATUS_COLORS[status]}`}>
              {STATUS_LABELS[status]}
            </span>
          </div>

          {/* What each person said */}
          {compReflections.length > 0 && (
            <div className="mt-4 mb-4">
              <p className="text-xs text-stone-400 uppercase tracking-wide font-medium mb-2">What each person said</p>
              <div
                className="grid gap-3"
                style={{ gridTemplateColumns: `repeat(${Math.max(compReflections.length, 1)}, minmax(0, 1fr))` }}
              >
                {compReflections.map(r => (
                  <div key={r.member_id} className="bg-stone-50 rounded-xl p-3">
                    <p className="text-xs font-semibold text-stone-500 mb-1">{r.display_name}</p>
                    <p className="text-xs text-stone-700">{formatResponse(r.response_data)}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* AI alignment comment */}
          {aiComments[activeComponent] && (
            <div className={`rounded-xl p-4 mb-4 text-sm ${isFlagged ? 'bg-amber-50 text-amber-900' : 'bg-green-50 text-green-900'}`}>
              <p className="text-xs font-semibold uppercase tracking-wide opacity-60 mb-1">
                {isFlagged ? 'Alignment gap' : 'Arbour summary'}
              </p>
              <p>{aiComments[activeComponent]}</p>
            </div>
          )}

          {/* Resolution note (flagged only) */}
          {isFlagged && !fullyApproved && (
            <div className="mb-4">
              <label className="block text-sm font-medium text-stone-700 mb-1">
                Resolution note
                <span className="text-stone-400 font-normal ml-1">: what did you discuss and decide?</span>
              </label>
              <textarea
                className="w-full border border-amber-200 rounded-lg px-3 py-2 text-sm text-stone-800 resize-none focus:outline-none focus:ring-2 focus:ring-amber-400"
                rows={2}
                value={resolutionNote}
                onChange={e => setResolutionNote(e.target.value)}
                placeholder={RESOLUTION_PLACEHOLDERS[activeComponent]}
              />
              <p className="text-xs text-stone-400 mt-1">Anyone on the team can write this. Your teammates will see it once the draft is generated.</p>
              <button
                onClick={() => generateDraft(activeComponent, teamId, resolutionNote)}
                disabled={generating[activeComponent] || !resolutionNote.trim()}
                className="mt-2 w-full border border-green-600 text-green-700 rounded-lg py-2 text-sm font-medium hover:bg-green-50 disabled:opacity-40 transition"
              >
                {generating[activeComponent] ? 'Generating agreement…' : ag?.draft_text ? 'Regenerate with new note' : 'Generate agreement draft'}
              </button>
            </div>
          )}

          {/* Non-flagged: show generate button if no draft yet */}
          {!isFlagged && !ag?.final_text && (
            <div className="mb-4 py-3 text-center text-sm text-stone-400">
              {generating[activeComponent] ? 'Arbour is drafting your agreement…' : 'Generating agreement…'}
            </div>
          )}

          {/* Agreement draft */}
          {ag?.final_text && (
            <div className="mb-4">
              <label className="block text-sm font-medium text-stone-700 mb-1">Agreement</label>
              <textarea
                className="w-full border border-stone-200 rounded-lg px-3 py-2 text-sm text-stone-800 resize-none focus:outline-none focus:ring-2 focus:ring-green-500"
                rows={4}
                value={editText}
                onChange={e => { setEditText(e.target.value); setEditDirty(true); editDirtyRef.current = true }}
                disabled={fullyApproved}
              />
              <div className="flex items-center justify-between mt-1">
                {ag.recorded_by && (
                  <span className="text-xs text-stone-400">
                    Last edited by {members.find(m => m.id === ag.recorded_by)?.display_name ?? 'teammate'}
                  </span>
                )}
                {!fullyApproved && editText !== ag?.final_text && (
                  <button
                    onClick={handleSaveText}
                    disabled={saving}
                    className="text-sm text-green-700 hover:underline ml-auto"
                  >
                    {saving ? 'Saving…' : 'Save edits'}
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Approval section */}
          {ag?.final_text && (
            <div className="border-t border-stone-100 pt-4">
              <div className="flex items-center justify-between mb-3">
                <span className="text-sm font-medium text-stone-600">
                  Approvals: {compApprovals.length} / {teamSize}
                </span>
                <div className="flex gap-2">
                  {members.map(m => (
                    <span
                      key={m.id}
                      className={`text-xs px-2 py-1 rounded-full ${
                        compApprovals.some(a => a.member_id === m.id)
                          ? 'bg-green-100 text-green-700'
                          : 'bg-stone-100 text-stone-400'
                      }`}
                    >
                      {m.display_name}
                    </span>
                  ))}
                </div>
              </div>

              {fullyApproved ? (
                <div className="text-center text-green-700 font-medium text-sm py-2">✓ All agreed</div>
              ) : myApproval ? (
                <div className="flex items-center gap-3">
                  <div className="flex-1 text-sm text-green-700 font-medium">✓ You approved this</div>
                  <button
                    onClick={handleWithdraw}
                    className="text-xs text-stone-400 hover:text-stone-600 hover:underline"
                  >
                    Withdraw
                  </button>
                </div>
              ) : (
                <button
                  onClick={handleApprove}
                  className="w-full bg-green-700 text-white rounded-lg py-2.5 text-sm font-medium hover:bg-green-800 transition"
                >
                  Approve this agreement
                </button>
              )}
            </div>
          )}
        </div>

        {/* Continue button */}
        {allDone ? (
          <div className="flex flex-col gap-3">
            <button
              onClick={() => router.push(`/${code}/create-tasks`)}
              className="w-full bg-green-700 text-white rounded-xl py-4 text-lg font-medium hover:bg-green-800 transition"
            >
              Set up tasks →
            </button>
            <button
              onClick={() => router.push(`/${code}/charter`)}
              className="w-full text-sm text-stone-500 hover:text-stone-700 transition py-2"
            >
              View collaboration agreement
            </button>
          </div>
        ) : (
          <div className="text-center text-sm text-stone-400 py-2">
            {CHAT_COMPONENTS.length - totalApproved} component{CHAT_COMPONENTS.length - totalApproved !== 1 ? 's' : ''} still need agreement
          </div>
        )}
      </div>
    </main>
  )
}
